# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviews do
  @moduledoc """
  Require at least one approving review on a pull request, before merging. Set to `null` to disable.
  """

  @derive [Poison.Encoder]
  defstruct [
    :dismissal_restrictions,
    :dismiss_stale_reviews,
    :require_code_owner_reviews,
    :required_approving_review_count
  ]

  @type t :: %__MODULE__{
          :dismissal_restrictions =>
            ExOctocat.Model.ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviewsDismissalRestrictions.t()
            | nil,
          :dismiss_stale_reviews => boolean() | nil,
          :require_code_owner_reviews => boolean() | nil,
          :required_approving_review_count => integer() | nil
        }
end

defimpl Poison.Decoder,
  for: ExOctocat.Model.ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviews do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :dismissal_restrictions,
      :struct,
      ExOctocat.Model.ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviewsDismissalRestrictions,
      options
    )
  end
end
