# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ReposOwnerRepoEnvironmentsEnvironmentNameReviewers do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :id
  ]

  @type t :: %__MODULE__{
          :type => ExOctocat.Model.DeploymentReviewerType.t() | nil,
          :id => integer() | nil
        }
end

defimpl Poison.Decoder,
  for: ExOctocat.Model.ReposOwnerRepoEnvironmentsEnvironmentNameReviewers do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:type, :struct, ExOctocat.Model.DeploymentReviewerType, options)
  end
end
