# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ReposOwnerRepoSecurityAndAnalysisSecretScanning do
  @moduledoc """
  Use the `status` property to enable or disable secret scanning for this repository. For more information, see \"[About secret scanning](/code-security/secret-security/about-secret-scanning).\"
  """

  @derive [Poison.Encoder]
  defstruct [
    :status
  ]

  @type t :: %__MODULE__{
          :status => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ReposOwnerRepoSecurityAndAnalysisSecretScanning do
  def decode(value, _options) do
    value
  end
end
