# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ScimV2OrganizationsOrgUsersScimUserIdOperations do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :op,
    :path,
    :value
  ]

  @type t :: %__MODULE__{
          :op => String.t(),
          :path => String.t() | nil,
          :value => OneOfobjectarraystring | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ScimV2OrganizationsOrgUsersScimUserIdOperations do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:value, :struct, ExOctocat.Model.OneOfobjectarraystring, options)
  end
end
