# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ScimV2EnterprisesEnterpriseUsersEmails do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :value,
    :type,
    :primary
  ]

  @type t :: %__MODULE__{
          :value => String.t(),
          :type => String.t(),
          :primary => boolean()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ScimV2EnterprisesEnterpriseUsersEmails do
  def decode(value, _options) do
    value
  end
end
