# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ActionsBillingUsage do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total_minutes_used,
    :total_paid_minutes_used,
    :included_minutes,
    :minutes_used_breakdown
  ]

  @type t :: %__MODULE__{
          :total_minutes_used => integer(),
          :total_paid_minutes_used => integer(),
          :included_minutes => integer(),
          :minutes_used_breakdown =>
            ExOctocat.Model.ActionsBillingUsageMinutesUsedBreakdown.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ActionsBillingUsage do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :minutes_used_breakdown,
      :struct,
      ExOctocat.Model.ActionsBillingUsageMinutesUsedBreakdown,
      options
    )
  end
end
