# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ActionsRepositoryPermissions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :enabled,
    :allowed_actions,
    :selected_actions_url
  ]

  @type t :: %__MODULE__{
          :enabled => boolean(),
          :allowed_actions => ExOctocat.Model.AllowedActions.t() | nil,
          :selected_actions_url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ActionsRepositoryPermissions do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:allowed_actions, :struct, ExOctocat.Model.AllowedActions, options)
  end
end
