# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.AllowedActions do
  @moduledoc """
  The permissions policy that controls the actions that are allowed to run. Can be one of: `all`, `local_only`, or `selected`.
  """

  @derive [Poison.Encoder]
  defstruct []

  @type t :: %__MODULE__{}
end

defimpl Poison.Decoder, for: ExOctocat.Model.AllowedActions do
  def decode(value, _options) do
    value
  end
end
