# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ApiOverviewSshKeyFingerprints do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :SHA256_RSA,
    :SHA256_DSA
  ]

  @type t :: %__MODULE__{
          :SHA256_RSA => String.t() | nil,
          :SHA256_DSA => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ApiOverviewSshKeyFingerprints do
  def decode(value, _options) do
    value
  end
end
