# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.Authorization do
  @moduledoc """
  The authorization for an OAuth app, GitHub App, or a Personal Access Token.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :url,
    :scopes,
    :token,
    :token_last_eight,
    :hashed_token,
    :app,
    :note,
    :note_url,
    :updated_at,
    :created_at,
    :fingerprint,
    :user,
    :installation
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :url => String.t(),
          :scopes => [String.t()] | nil,
          :token => String.t(),
          :token_last_eight => String.t() | nil,
          :hashed_token => String.t() | nil,
          :app => ExOctocat.Model.ApplicationGrantApp.t(),
          :note => String.t() | nil,
          :note_url => String.t() | nil,
          :updated_at => DateTime.t(),
          :created_at => DateTime.t(),
          :fingerprint => String.t() | nil,
          :user => SimpleUser | nil,
          :installation => ScopedInstallation | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.Authorization do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:app, :struct, ExOctocat.Model.ApplicationGrantApp, options)
    |> deserialize(:user, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:installation, :struct, ExOctocat.Model.ScopedInstallation, options)
  end
end
