# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.AuthenticationToken do
  @moduledoc """
  Authentication Token
  """

  @derive [Poison.Encoder]
  defstruct [
    :token,
    :expires_at,
    :permissions,
    :repositories,
    :single_file,
    :repository_selection
  ]

  @type t :: %__MODULE__{
          :token => String.t(),
          :expires_at => DateTime.t(),
          :permissions => map() | nil,
          :repositories => [ExOctocat.Model.Repository.t()] | nil,
          :single_file => String.t() | nil,
          :repository_selection => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.AuthenticationToken do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:repositories, :list, ExOctocat.Model.Repository, options)
  end
end
