# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.AutoMerge do
  @moduledoc """
  The status of auto merging a pull request.
  """

  @derive [Poison.Encoder]
  defstruct [
    :enabled_by,
    :merge_method,
    :commit_title,
    :commit_message
  ]

  @type t :: %__MODULE__{
          :enabled_by => ExOctocat.Model.SimpleUser.t() | nil,
          :merge_method => String.t(),
          :commit_title => String.t(),
          :commit_message => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.AutoMerge do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:enabled_by, :struct, ExOctocat.Model.SimpleUser, options)
  end
end
