# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.BaseGist do
  @moduledoc """
  Base Gist
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :forks_url,
    :commits_url,
    :id,
    :node_id,
    :git_pull_url,
    :git_push_url,
    :html_url,
    :files,
    :public,
    :created_at,
    :updated_at,
    :description,
    :comments,
    :user,
    :comments_url,
    :owner,
    :truncated,
    :forks,
    :history
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :forks_url => String.t(),
          :commits_url => String.t(),
          :id => String.t(),
          :node_id => String.t(),
          :git_pull_url => String.t(),
          :git_push_url => String.t(),
          :html_url => String.t(),
          :files => %{optional(String.t()) => ExOctocat.Model.BaseGistFiles.t()},
          :public => boolean(),
          :created_at => DateTime.t(),
          :updated_at => DateTime.t(),
          :description => String.t() | nil,
          :comments => integer(),
          :user => SimpleUser | nil,
          :comments_url => String.t(),
          :owner => SimpleUser | nil,
          :truncated => boolean() | nil,
          :forks => [AnyType] | nil,
          :history => [AnyType] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.BaseGist do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:files, :map, ExOctocat.Model.BaseGistFiles, options)
    |> deserialize(:user, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:owner, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:forks, :list, ExOctocat.Model.AnyType, options)
    |> deserialize(:history, :list, ExOctocat.Model.AnyType, options)
  end
end
