# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.BranchRestrictionPolicyApps do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :slug,
    :node_id,
    :owner,
    :name,
    :description,
    :external_url,
    :html_url,
    :created_at,
    :updated_at,
    :permissions,
    :events
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :slug => String.t() | nil,
          :node_id => String.t() | nil,
          :owner => ExOctocat.Model.BranchRestrictionPolicyOwner.t() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :external_url => String.t() | nil,
          :html_url => String.t() | nil,
          :created_at => String.t() | nil,
          :updated_at => String.t() | nil,
          :permissions => ExOctocat.Model.BranchRestrictionPolicyPermissions.t() | nil,
          :events => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.BranchRestrictionPolicyApps do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:owner, :struct, ExOctocat.Model.BranchRestrictionPolicyOwner, options)
    |> deserialize(
      :permissions,
      :struct,
      ExOctocat.Model.BranchRestrictionPolicyPermissions,
      options
    )
  end
end
