# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.BranchShort do
  @moduledoc """
  Branch Short
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :commit,
    :protected
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :commit => ExOctocat.Model.BranchShortCommit.t(),
          :protected => boolean()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.BranchShort do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:commit, :struct, ExOctocat.Model.BranchShortCommit, options)
  end
end
