# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.BranchWithProtectionLinks do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :html,
    :self
  ]

  @type t :: %__MODULE__{
          :html => String.t(),
          :self => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.BranchWithProtectionLinks do
  def decode(value, _options) do
    value
  end
end
