# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.BranchProtection do
  @moduledoc """
  Branch Protection
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :enabled,
    :required_status_checks,
    :enforce_admins,
    :required_pull_request_reviews,
    :restrictions,
    :required_linear_history,
    :allow_force_pushes,
    :allow_deletions,
    :required_conversation_resolution,
    :name,
    :protection_url,
    :required_signatures
  ]

  @type t :: %__MODULE__{
          :url => String.t() | nil,
          :enabled => boolean() | nil,
          :required_status_checks =>
            ExOctocat.Model.BranchProtectionRequiredStatusChecks.t() | nil,
          :enforce_admins => ExOctocat.Model.ProtectedBranchAdminEnforced.t() | nil,
          :required_pull_request_reviews =>
            ExOctocat.Model.ProtectedBranchPullRequestReview.t() | nil,
          :restrictions => ExOctocat.Model.BranchRestrictionPolicy.t() | nil,
          :required_linear_history =>
            ExOctocat.Model.BranchProtectionRequiredLinearHistory.t() | nil,
          :allow_force_pushes =>
            ExOctocat.Model.BranchProtectionRequiredLinearHistory.t() | nil,
          :allow_deletions =>
            ExOctocat.Model.BranchProtectionRequiredLinearHistory.t() | nil,
          :required_conversation_resolution =>
            ExOctocat.Model.BranchProtectionRequiredLinearHistory.t() | nil,
          :name => String.t() | nil,
          :protection_url => String.t() | nil,
          :required_signatures =>
            ExOctocat.Model.BranchProtectionRequiredSignatures.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.BranchProtection do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :required_status_checks,
      :struct,
      ExOctocat.Model.BranchProtectionRequiredStatusChecks,
      options
    )
    |> deserialize(
      :enforce_admins,
      :struct,
      ExOctocat.Model.ProtectedBranchAdminEnforced,
      options
    )
    |> deserialize(
      :required_pull_request_reviews,
      :struct,
      ExOctocat.Model.ProtectedBranchPullRequestReview,
      options
    )
    |> deserialize(:restrictions, :struct, ExOctocat.Model.BranchRestrictionPolicy, options)
    |> deserialize(
      :required_linear_history,
      :struct,
      ExOctocat.Model.BranchProtectionRequiredLinearHistory,
      options
    )
    |> deserialize(
      :allow_force_pushes,
      :struct,
      ExOctocat.Model.BranchProtectionRequiredLinearHistory,
      options
    )
    |> deserialize(
      :allow_deletions,
      :struct,
      ExOctocat.Model.BranchProtectionRequiredLinearHistory,
      options
    )
    |> deserialize(
      :required_conversation_resolution,
      :struct,
      ExOctocat.Model.BranchProtectionRequiredLinearHistory,
      options
    )
    |> deserialize(
      :required_signatures,
      :struct,
      ExOctocat.Model.BranchProtectionRequiredSignatures,
      options
    )
  end
end
