# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.BranchProtectionRequiredLinearHistory do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :enabled
  ]

  @type t :: %__MODULE__{
          :enabled => boolean() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.BranchProtectionRequiredLinearHistory do
  def decode(value, _options) do
    value
  end
end
