# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.BranchWithProtection do
  @moduledoc """
  Branch With Protection
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :commit,
    :_links,
    :protected,
    :protection,
    :protection_url,
    :pattern,
    :required_approving_review_count
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :commit => ExOctocat.Model.Commit.t(),
          :_links => ExOctocat.Model.BranchWithProtectionLinks.t(),
          :protected => boolean(),
          :protection => ExOctocat.Model.BranchProtection.t(),
          :protection_url => String.t(),
          :pattern => String.t() | nil,
          :required_approving_review_count => integer() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.BranchWithProtection do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:commit, :struct, ExOctocat.Model.Commit, options)
    |> deserialize(:_links, :struct, ExOctocat.Model.BranchWithProtectionLinks, options)
    |> deserialize(:protection, :struct, ExOctocat.Model.BranchProtection, options)
  end
end
