# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.CheckRun do
  @moduledoc """
  A check performed on the code of a given code change
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :head_sha,
    :node_id,
    :external_id,
    :url,
    :html_url,
    :details_url,
    :status,
    :conclusion,
    :started_at,
    :completed_at,
    :output,
    :name,
    :check_suite,
    :app,
    :pull_requests,
    :deployment
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :head_sha => String.t(),
          :node_id => String.t(),
          :external_id => String.t() | nil,
          :url => String.t(),
          :html_url => String.t() | nil,
          :details_url => String.t() | nil,
          :status => String.t(),
          :conclusion => String.t() | nil,
          :started_at => DateTime.t() | nil,
          :completed_at => DateTime.t() | nil,
          :output => ExOctocat.Model.CheckRunOutput.t(),
          :name => String.t(),
          :check_suite => ExOctocat.Model.CheckRunCheckSuite.t() | nil,
          :app => Integration | nil,
          :pull_requests => [ExOctocat.Model.PullRequestMinimal.t()],
          :deployment => ExOctocat.Model.DeploymentSimple.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.CheckRun do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:output, :struct, ExOctocat.Model.CheckRunOutput, options)
    |> deserialize(:check_suite, :struct, ExOctocat.Model.CheckRunCheckSuite, options)
    |> deserialize(:app, :struct, ExOctocat.Model.Integration, options)
    |> deserialize(:pull_requests, :list, ExOctocat.Model.PullRequestMinimal, options)
    |> deserialize(:deployment, :struct, ExOctocat.Model.DeploymentSimple, options)
  end
end
