# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.CheckRunOutput do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :summary,
    :text,
    :annotations_count,
    :annotations_url
  ]

  @type t :: %__MODULE__{
          :title => String.t() | nil,
          :summary => String.t() | nil,
          :text => String.t() | nil,
          :annotations_count => integer(),
          :annotations_url => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.CheckRunOutput do
  def decode(value, _options) do
    value
  end
end
