# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.CheckSuitePreference do
  @moduledoc """
  Check suite configuration preferences for a repository.
  """

  @derive [Poison.Encoder]
  defstruct [
    :preferences,
    :repository
  ]

  @type t :: %__MODULE__{
          :preferences => ExOctocat.Model.CheckSuitePreferencePreferences.t(),
          :repository => ExOctocat.Model.MinimalRepository.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.CheckSuitePreference do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :preferences,
      :struct,
      ExOctocat.Model.CheckSuitePreferencePreferences,
      options
    )
    |> deserialize(:repository, :struct, ExOctocat.Model.MinimalRepository, options)
  end
end
