# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.CodeScanningAnalysis do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ref,
    :commit_sha,
    :analysis_key,
    :environment,
    :category,
    :error,
    :created_at,
    :results_count,
    :rules_count,
    :id,
    :url,
    :sarif_id,
    :tool,
    :deletable,
    :warning,
    :tool_name
  ]

  @type t :: %__MODULE__{
          :ref => String.t(),
          :commit_sha => String.t(),
          :analysis_key => String.t(),
          :environment => String.t(),
          :category => String.t() | nil,
          :error => String.t(),
          :created_at => DateTime.t(),
          :results_count => integer(),
          :rules_count => integer(),
          :id => integer(),
          :url => String.t(),
          :sarif_id => String.t(),
          :tool => ExOctocat.Model.CodeScanningAnalysisTool.t(),
          :deletable => boolean(),
          :warning => String.t(),
          :tool_name => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.CodeScanningAnalysis do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:tool, :struct, ExOctocat.Model.CodeScanningAnalysisTool, options)
  end
end
