# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.CodeScanningAnalysisTool do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :version,
    :guid
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :version => String.t() | nil,
          :guid => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.CodeScanningAnalysisTool do
  def decode(value, _options) do
    value
  end
end
