# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.CombinedCommitStatus do
  @moduledoc """
  Combined Commit Status
  """

  @derive [Poison.Encoder]
  defstruct [
    :state,
    :statuses,
    :sha,
    :total_count,
    :repository,
    :commit_url,
    :url
  ]

  @type t :: %__MODULE__{
          :state => String.t(),
          :statuses => [ExOctocat.Model.SimpleCommitStatus.t()],
          :sha => String.t(),
          :total_count => integer(),
          :repository => ExOctocat.Model.MinimalRepository.t(),
          :commit_url => String.t(),
          :url => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.CombinedCommitStatus do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:statuses, :list, ExOctocat.Model.SimpleCommitStatus, options)
    |> deserialize(:repository, :struct, ExOctocat.Model.MinimalRepository, options)
  end
end
