# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.CommunityProfileFiles do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :code_of_conduct,
    :code_of_conduct_file,
    :license,
    :contributing,
    :readme,
    :issue_template,
    :pull_request_template
  ]

  @type t :: %__MODULE__{
          :code_of_conduct => CodeOfConductSimple | nil,
          :code_of_conduct_file => CommunityHealthFile | nil,
          :license => LicenseSimple | nil,
          :contributing => CommunityHealthFile | nil,
          :readme => CommunityHealthFile | nil,
          :issue_template => CommunityHealthFile | nil,
          :pull_request_template => CommunityHealthFile | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.CommunityProfileFiles do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:code_of_conduct, :struct, ExOctocat.Model.CodeOfConductSimple, options)
    |> deserialize(
      :code_of_conduct_file,
      :struct,
      ExOctocat.Model.CommunityHealthFile,
      options
    )
    |> deserialize(:license, :struct, ExOctocat.Model.LicenseSimple, options)
    |> deserialize(:contributing, :struct, ExOctocat.Model.CommunityHealthFile, options)
    |> deserialize(:readme, :struct, ExOctocat.Model.CommunityHealthFile, options)
    |> deserialize(:issue_template, :struct, ExOctocat.Model.CommunityHealthFile, options)
    |> deserialize(
      :pull_request_template,
      :struct,
      ExOctocat.Model.CommunityHealthFile,
      options
    )
  end
end
