# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.CommitActivity do
  @moduledoc """
  Commit Activity
  """

  @derive [Poison.Encoder]
  defstruct [
    :days,
    :total,
    :week
  ]

  @type t :: %__MODULE__{
          :days => [integer()],
          :total => integer(),
          :week => integer()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.CommitActivity do
  def decode(value, _options) do
    value
  end
end
