# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.CommitComparison do
  @moduledoc """
  Commit Comparison
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :html_url,
    :permalink_url,
    :diff_url,
    :patch_url,
    :base_commit,
    :merge_base_commit,
    :status,
    :ahead_by,
    :behind_by,
    :total_commits,
    :commits,
    :files
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :html_url => String.t(),
          :permalink_url => String.t(),
          :diff_url => String.t(),
          :patch_url => String.t(),
          :base_commit => ExOctocat.Model.Commit.t(),
          :merge_base_commit => ExOctocat.Model.Commit.t(),
          :status => String.t(),
          :ahead_by => integer(),
          :behind_by => integer(),
          :total_commits => integer(),
          :commits => [ExOctocat.Model.Commit.t()],
          :files => [ExOctocat.Model.DiffEntry.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.CommitComparison do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:base_commit, :struct, ExOctocat.Model.Commit, options)
    |> deserialize(:merge_base_commit, :struct, ExOctocat.Model.Commit, options)
    |> deserialize(:commits, :list, ExOctocat.Model.Commit, options)
    |> deserialize(:files, :list, ExOctocat.Model.DiffEntry, options)
  end
end
