# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.CommitCommit do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :author,
    :committer,
    :message,
    :comment_count,
    :tree,
    :verification
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :author => GitUser | nil,
          :committer => GitUser | nil,
          :message => String.t(),
          :comment_count => integer(),
          :tree => ExOctocat.Model.CommitCommitTree.t(),
          :verification => ExOctocat.Model.Verification.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.CommitCommit do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:author, :struct, ExOctocat.Model.GitUser, options)
    |> deserialize(:committer, :struct, ExOctocat.Model.GitUser, options)
    |> deserialize(:tree, :struct, ExOctocat.Model.CommitCommitTree, options)
    |> deserialize(:verification, :struct, ExOctocat.Model.Verification, options)
  end
end
