# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ContentTree do
  @moduledoc """
  Content Tree
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :size,
    :name,
    :path,
    :sha,
    :url,
    :git_url,
    :html_url,
    :download_url,
    :entries,
    :_links
  ]

  @type t :: %__MODULE__{
          :type => String.t(),
          :size => integer(),
          :name => String.t(),
          :path => String.t(),
          :sha => String.t(),
          :url => String.t(),
          :git_url => String.t() | nil,
          :html_url => String.t() | nil,
          :download_url => String.t() | nil,
          :entries => [ExOctocat.Model.ContentTreeEntries.t()] | nil,
          :_links => ExOctocat.Model.ContentTreeLinks.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ContentTree do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:entries, :list, ExOctocat.Model.ContentTreeEntries, options)
    |> deserialize(:_links, :struct, ExOctocat.Model.ContentTreeLinks, options)
  end
end
