# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.EnvironmentApprovals do
  @moduledoc """
  An entry in the reviews log for environment deployments
  """

  @derive [Poison.Encoder]
  defstruct [
    :environments,
    :state,
    :user,
    :comment
  ]

  @type t :: %__MODULE__{
          :environments => [ExOctocat.Model.EnvironmentApprovalsEnvironments.t()],
          :state => String.t(),
          :user => ExOctocat.Model.SimpleUser.t() | nil,
          :comment => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.EnvironmentApprovals do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :environments,
      :list,
      ExOctocat.Model.EnvironmentApprovalsEnvironments,
      options
    )
    |> deserialize(:user, :struct, ExOctocat.Model.SimpleUser, options)
  end
end
