# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.EventPayload do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :issue,
    :comment,
    :pages
  ]

  @type t :: %__MODULE__{
          :action => String.t() | nil,
          :issue => ExOctocat.Model.IssueSimple.t() | nil,
          :comment => ExOctocat.Model.IssueComment.t() | nil,
          :pages => [ExOctocat.Model.EventPayloadPages.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.EventPayload do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:issue, :struct, ExOctocat.Model.IssueSimple, options)
    |> deserialize(:comment, :struct, ExOctocat.Model.IssueComment, options)
    |> deserialize(:pages, :list, ExOctocat.Model.EventPayloadPages, options)
  end
end
