# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.FeedLinks do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :timeline,
    :user,
    :security_advisories,
    :current_user,
    :current_user_public,
    :current_user_actor,
    :current_user_organization,
    :current_user_organizations
  ]

  @type t :: %__MODULE__{
          :timeline => ExOctocat.Model.LinkWithType.t(),
          :user => ExOctocat.Model.LinkWithType.t(),
          :security_advisories => ExOctocat.Model.LinkWithType.t() | nil,
          :current_user => ExOctocat.Model.LinkWithType.t() | nil,
          :current_user_public => ExOctocat.Model.LinkWithType.t() | nil,
          :current_user_actor => ExOctocat.Model.LinkWithType.t() | nil,
          :current_user_organization => ExOctocat.Model.LinkWithType.t() | nil,
          :current_user_organizations => [ExOctocat.Model.LinkWithType.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.FeedLinks do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:timeline, :struct, ExOctocat.Model.LinkWithType, options)
    |> deserialize(:user, :struct, ExOctocat.Model.LinkWithType, options)
    |> deserialize(:security_advisories, :struct, ExOctocat.Model.LinkWithType, options)
    |> deserialize(:current_user, :struct, ExOctocat.Model.LinkWithType, options)
    |> deserialize(:current_user_public, :struct, ExOctocat.Model.LinkWithType, options)
    |> deserialize(:current_user_actor, :struct, ExOctocat.Model.LinkWithType, options)
    |> deserialize(
      :current_user_organization,
      :struct,
      ExOctocat.Model.LinkWithType,
      options
    )
    |> deserialize(
      :current_user_organizations,
      :list,
      ExOctocat.Model.LinkWithType,
      options
    )
  end
end
