# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.FileCommitCommit do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :sha,
    :node_id,
    :url,
    :html_url,
    :author,
    :committer,
    :message,
    :tree,
    :parents,
    :verification
  ]

  @type t :: %__MODULE__{
          :sha => String.t() | nil,
          :node_id => String.t() | nil,
          :url => String.t() | nil,
          :html_url => String.t() | nil,
          :author => ExOctocat.Model.FileCommitCommitAuthor.t() | nil,
          :committer => ExOctocat.Model.FileCommitCommitAuthor.t() | nil,
          :message => String.t() | nil,
          :tree => ExOctocat.Model.FileCommitCommitTree.t() | nil,
          :parents => [ExOctocat.Model.FileCommitCommitParents.t()] | nil,
          :verification => ExOctocat.Model.FileCommitCommitVerification.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.FileCommitCommit do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:author, :struct, ExOctocat.Model.FileCommitCommitAuthor, options)
    |> deserialize(:committer, :struct, ExOctocat.Model.FileCommitCommitAuthor, options)
    |> deserialize(:tree, :struct, ExOctocat.Model.FileCommitCommitTree, options)
    |> deserialize(:parents, :list, ExOctocat.Model.FileCommitCommitParents, options)
    |> deserialize(
      :verification,
      :struct,
      ExOctocat.Model.FileCommitCommitVerification,
      options
    )
  end
end
