# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.FileCommitCommitAuthor do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :date,
    :name,
    :email
  ]

  @type t :: %__MODULE__{
          :date => String.t() | nil,
          :name => String.t() | nil,
          :email => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.FileCommitCommitAuthor do
  def decode(value, _options) do
    value
  end
end
