# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.FullRepositorySecurityAndAnalysis do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :advanced_security,
    :secret_scanning
  ]

  @type t :: %__MODULE__{
          :advanced_security =>
            ExOctocat.Model.FullRepositorySecurityAndAnalysisAdvancedSecurity.t() | nil,
          :secret_scanning =>
            ExOctocat.Model.FullRepositorySecurityAndAnalysisAdvancedSecurity.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.FullRepositorySecurityAndAnalysis do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :advanced_security,
      :struct,
      ExOctocat.Model.FullRepositorySecurityAndAnalysisAdvancedSecurity,
      options
    )
    |> deserialize(
      :secret_scanning,
      :struct,
      ExOctocat.Model.FullRepositorySecurityAndAnalysisAdvancedSecurity,
      options
    )
  end
end
