# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.GistHistory do
  @moduledoc """
  Gist History
  """

  @derive [Poison.Encoder]
  defstruct [
    :user,
    :version,
    :committed_at,
    :change_status,
    :url
  ]

  @type t :: %__MODULE__{
          :user => ExOctocat.Model.SimpleUser.t() | nil,
          :version => String.t() | nil,
          :committed_at => DateTime.t() | nil,
          :change_status => ExOctocat.Model.GistHistoryChangeStatus.t() | nil,
          :url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.GistHistory do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:user, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(
      :change_status,
      :struct,
      ExOctocat.Model.GistHistoryChangeStatus,
      options
    )
  end
end
