# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.GistSimpleForks do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :url,
    :user,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :url => String.t() | nil,
          :user => ExOctocat.Model.PublicUser.t() | nil,
          :created_at => DateTime.t() | nil,
          :updated_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.GistSimpleForks do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:user, :struct, ExOctocat.Model.PublicUser, options)
  end
end
