# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.GitRef do
  @moduledoc """
  Git references within a repository
  """

  @derive [Poison.Encoder]
  defstruct [
    :ref,
    :node_id,
    :url,
    :object
  ]

  @type t :: %__MODULE__{
          :ref => String.t(),
          :node_id => String.t(),
          :url => String.t(),
          :object => ExOctocat.Model.GitRefObject.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.GitRef do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:object, :struct, ExOctocat.Model.GitRefObject, options)
  end
end
