# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.GitTag do
  @moduledoc """
  Metadata for a Git tag
  """

  @derive [Poison.Encoder]
  defstruct [
    :node_id,
    :tag,
    :sha,
    :url,
    :message,
    :tagger,
    :object,
    :verification
  ]

  @type t :: %__MODULE__{
          :node_id => String.t(),
          :tag => String.t(),
          :sha => String.t(),
          :url => String.t(),
          :message => String.t(),
          :tagger => ExOctocat.Model.GitTagTagger.t(),
          :object => ExOctocat.Model.GitTagObject.t(),
          :verification => ExOctocat.Model.Verification.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.GitTag do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:tagger, :struct, ExOctocat.Model.GitTagTagger, options)
    |> deserialize(:object, :struct, ExOctocat.Model.GitTagObject, options)
    |> deserialize(:verification, :struct, ExOctocat.Model.Verification, options)
  end
end
