# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.GitignoreTemplate do
  @moduledoc """
  Gitignore Template
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :source
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :source => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.GitignoreTemplate do
  def decode(value, _options) do
    value
  end
end
