# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.GpgKey do
  @moduledoc """
  A unique encryption key
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :primary_key_id,
    :key_id,
    :public_key,
    :emails,
    :subkeys,
    :can_sign,
    :can_encrypt_comms,
    :can_encrypt_storage,
    :can_certify,
    :created_at,
    :expires_at,
    :raw_key
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :primary_key_id => integer() | nil,
          :key_id => String.t(),
          :public_key => String.t(),
          :emails => [ExOctocat.Model.GpgKeyEmails.t()],
          :subkeys => [ExOctocat.Model.GpgKeySubkeys.t()],
          :can_sign => boolean(),
          :can_encrypt_comms => boolean(),
          :can_encrypt_storage => boolean(),
          :can_certify => boolean(),
          :created_at => DateTime.t(),
          :expires_at => DateTime.t() | nil,
          :raw_key => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.GpgKey do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:emails, :list, ExOctocat.Model.GpgKeyEmails, options)
    |> deserialize(:subkeys, :list, ExOctocat.Model.GpgKeySubkeys, options)
  end
end
