# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.GroupMapping do
  @moduledoc """
  External Groups to be mapped to a team for membership
  """

  @derive [Poison.Encoder]
  defstruct [
    :groups
  ]

  @type t :: %__MODULE__{
          :groups => [ExOctocat.Model.GroupMappingGroups.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.GroupMapping do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:groups, :list, ExOctocat.Model.GroupMappingGroups, options)
  end
end
