# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.HookDelivery do
  @moduledoc """
  Delivery made by a webhook.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :guid,
    :delivered_at,
    :redelivery,
    :duration,
    :status,
    :status_code,
    :event,
    :action,
    :installation_id,
    :repository_id,
    :request,
    :response
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :guid => String.t(),
          :delivered_at => DateTime.t(),
          :redelivery => boolean(),
          :duration => float(),
          :status => String.t(),
          :status_code => integer(),
          :event => String.t(),
          :action => String.t() | nil,
          :installation_id => integer() | nil,
          :repository_id => integer() | nil,
          :request => ExOctocat.Model.HookDeliveryRequest.t(),
          :response => ExOctocat.Model.HookDeliveryResponse.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.HookDelivery do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:request, :struct, ExOctocat.Model.HookDeliveryRequest, options)
    |> deserialize(:response, :struct, ExOctocat.Model.HookDeliveryResponse, options)
  end
end
