# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.HookDeliveryResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :headers,
    :payload
  ]

  @type t :: %__MODULE__{
          :headers => %{optional(String.t()) => map()} | nil,
          :payload => %{optional(String.t()) => map()} | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.HookDeliveryResponse do
  def decode(value, _options) do
    value
  end
end
