# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.HookConfig do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :email,
    :password,
    :room,
    :subdomain,
    :url,
    :insecure_ssl,
    :content_type,
    :digest,
    :secret,
    :token
  ]

  @type t :: %__MODULE__{
          :email => String.t() | nil,
          :password => String.t() | nil,
          :room => String.t() | nil,
          :subdomain => String.t() | nil,
          :url => String.t() | nil,
          :insecure_ssl => ExOctocat.Model.WebhookConfigInsecureSsl.t() | nil,
          :content_type => String.t() | nil,
          :digest => String.t() | nil,
          :secret => String.t() | nil,
          :token => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.HookConfig do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :insecure_ssl,
      :struct,
      ExOctocat.Model.WebhookConfigInsecureSsl,
      options
    )
  end
end
