# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.Hovercard do
  @moduledoc """
  Hovercard
  """

  @derive [Poison.Encoder]
  defstruct [
    :contexts
  ]

  @type t :: %__MODULE__{
          :contexts => [ExOctocat.Model.HovercardContexts.t()]
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.Hovercard do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:contexts, :list, ExOctocat.Model.HovercardContexts, options)
  end
end
