# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ImportProjectChoices do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :vcs,
    :tfvc_project,
    :human_name
  ]

  @type t :: %__MODULE__{
          :vcs => String.t() | nil,
          :tfvc_project => String.t() | nil,
          :human_name => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ImportProjectChoices do
  def decode(value, _options) do
    value
  end
end
