# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject52 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :note,
    :archived
  ]

  @type t :: %__MODULE__{
          :note => String.t() | nil,
          :archived => boolean() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject52 do
  def decode(value, _options) do
    value
  end
end
