# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject17 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :files,
    :public
  ]

  @type t :: %__MODULE__{
          :description => String.t() | nil,
          :files => %{optional(String.t()) => ExOctocat.Model.GistsFiles.t()},
          :public => OneOfbooleanstring | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject17 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:files, :map, ExOctocat.Model.GistsFiles, options)
    |> deserialize(:public, :struct, ExOctocat.Model.OneOfbooleanstring, options)
  end
end
