# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject149 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :schemas,
    :Operations
  ]

  @type t :: %__MODULE__{
          :schemas => [String.t()] | nil,
          :Operations => [
            ExOctocat.Model.ScimV2OrganizationsOrgUsersScimUserIdOperations.t()
          ]
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject149 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :Operations,
      :list,
      ExOctocat.Model.ScimV2OrganizationsOrgUsersScimUserIdOperations,
      options
    )
  end
end
