# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineResponse403 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :block,
    :message,
    :documentation_url
  ]

  @type t :: %__MODULE__{
          :block => ExOctocat.Model.InlineResponse403Block.t() | nil,
          :message => String.t() | nil,
          :documentation_url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineResponse403 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:block, :struct, ExOctocat.Model.InlineResponse403Block, options)
  end
end
