# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject102 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :body,
    :assignee,
    :state,
    :milestone,
    :labels,
    :assignees
  ]

  @type t :: %__MODULE__{
          :title => OneOfstringinteger | nil,
          :body => String.t() | nil,
          :assignee => String.t() | nil,
          :state => String.t() | nil,
          :milestone => OneOfstringinteger | nil,
          :labels => [OneOfstringobject] | nil,
          :assignees => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject102 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:title, :struct, ExOctocat.Model.OneOfstringinteger, options)
    |> deserialize(:milestone, :struct, ExOctocat.Model.OneOfstringinteger, options)
    |> deserialize(:labels, :list, ExOctocat.Model.OneOfstringobject, options)
  end
end
