# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject88 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :sha,
    :force
  ]

  @type t :: %__MODULE__{
          :sha => String.t(),
          :force => boolean() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject88 do
  def decode(value, _options) do
    value
  end
end
