# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineResponse20028 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total_count,
    :repository_selection,
    :repositories
  ]

  @type t :: %__MODULE__{
          :total_count => integer(),
          :repository_selection => String.t() | nil,
          :repositories => [ExOctocat.Model.Repository.t()]
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineResponse20028 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:repositories, :list, ExOctocat.Model.Repository, options)
  end
end
