# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject148 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :schemas,
    :displayName,
    :externalId,
    :groups,
    :active,
    :userName,
    :name,
    :emails
  ]

  @type t :: %__MODULE__{
          :schemas => [String.t()] | nil,
          :displayName => String.t() | nil,
          :externalId => String.t() | nil,
          :groups => [String.t()] | nil,
          :active => boolean() | nil,
          :userName => String.t(),
          :name => ExOctocat.Model.ScimV2OrganizationsOrgUsersName.t(),
          :emails => [ExOctocat.Model.ScimV2OrganizationsOrgUsersScimUserIdEmails.t()]
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject148 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:name, :struct, ExOctocat.Model.ScimV2OrganizationsOrgUsersName, options)
    |> deserialize(
      :emails,
      :list,
      ExOctocat.Model.ScimV2OrganizationsOrgUsersScimUserIdEmails,
      options
    )
  end
end
