# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject86 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :message,
    :tree,
    :parents,
    :author,
    :committer,
    :signature
  ]

  @type t :: %__MODULE__{
          :message => String.t(),
          :tree => String.t(),
          :parents => [String.t()] | nil,
          :author => ExOctocat.Model.ReposOwnerRepoGitCommitsAuthor.t() | nil,
          :committer => ExOctocat.Model.ReposOwnerRepoGitCommitsCommitter.t() | nil,
          :signature => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject86 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :author,
      :struct,
      ExOctocat.Model.ReposOwnerRepoGitCommitsAuthor,
      options
    )
    |> deserialize(
      :committer,
      :struct,
      ExOctocat.Model.ReposOwnerRepoGitCommitsCommitter,
      options
    )
  end
end
