# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject134 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :state,
    :resolution
  ]

  @type t :: %__MODULE__{
          :state => ExOctocat.Model.SecretScanningAlertState.t(),
          :resolution => ExOctocat.Model.SecretScanningAlertResolution.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject134 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:state, :struct, ExOctocat.Model.SecretScanningAlertState, options)
    |> deserialize(
      :resolution,
      :struct,
      ExOctocat.Model.SecretScanningAlertResolution,
      options
    )
  end
end
