# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject115 do
  @moduledoc """
  The source branch and directory used to publish your Pages site.
  """

  @derive [Poison.Encoder]
  defstruct [
    :source
  ]

  @type t :: %__MODULE__{
          :source => ExOctocat.Model.ReposOwnerRepoPagesSource.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject115 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:source, :struct, ExOctocat.Model.ReposOwnerRepoPagesSource, options)
  end
end
