# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject160 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :groups,
    :synced_at
  ]

  @type t :: %__MODULE__{
          :groups => [ExOctocat.Model.TeamsTeamIdTeamSyncGroupMappingsGroups.t()],
          :synced_at => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject160 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :groups,
      :list,
      ExOctocat.Model.TeamsTeamIdTeamSyncGroupMappingsGroups,
      options
    )
  end
end
