# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineResponse20020 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total_count,
    :environments
  ]

  @type t :: %__MODULE__{
          :total_count => integer() | nil,
          :environments => [ExOctocat.Model.Environment.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineResponse20020 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:environments, :list, ExOctocat.Model.Environment, options)
  end
end
