# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineResponse20027 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total_count,
    :incomplete_results,
    :items
  ]

  @type t :: %__MODULE__{
          :total_count => integer(),
          :incomplete_results => boolean(),
          :items => [ExOctocat.Model.UserSearchResultItem.t()]
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineResponse20027 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:items, :list, ExOctocat.Model.UserSearchResultItem, options)
  end
end
