# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject142 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :schemas,
    :displayName,
    :members
  ]

  @type t :: %__MODULE__{
          :schemas => [String.t()],
          :displayName => String.t(),
          :members => [ExOctocat.Model.ScimV2EnterprisesEnterpriseGroupsMembers.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject142 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :members,
      :list,
      ExOctocat.Model.ScimV2EnterprisesEnterpriseGroupsMembers,
      options
    )
  end
end
