# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject78 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :message,
    :content,
    :sha,
    :branch,
    :committer,
    :author
  ]

  @type t :: %__MODULE__{
          :message => String.t(),
          :content => String.t(),
          :sha => String.t() | nil,
          :branch => String.t() | nil,
          :committer => ExOctocat.Model.ReposOwnerRepoContentsPathCommitter.t() | nil,
          :author => ExOctocat.Model.ReposOwnerRepoContentsPathAuthor.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject78 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :committer,
      :struct,
      ExOctocat.Model.ReposOwnerRepoContentsPathCommitter,
      options
    )
    |> deserialize(
      :author,
      :struct,
      ExOctocat.Model.ReposOwnerRepoContentsPathAuthor,
      options
    )
  end
end
