# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject65 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :required_status_checks,
    :enforce_admins,
    :required_pull_request_reviews,
    :restrictions,
    :required_linear_history,
    :allow_force_pushes,
    :allow_deletions,
    :required_conversation_resolution
  ]

  @type t :: %__MODULE__{
          :required_status_checks =>
            ExOctocat.Model.ReposOwnerRepoBranchesBranchProtectionRequiredStatusChecks.t()
            | nil,
          :enforce_admins => boolean() | nil,
          :required_pull_request_reviews =>
            ExOctocat.Model.ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviews.t()
            | nil,
          :restrictions =>
            ExOctocat.Model.ReposOwnerRepoBranchesBranchProtectionRestrictions.t() | nil,
          :required_linear_history => boolean() | nil,
          :allow_force_pushes => boolean() | nil,
          :allow_deletions => boolean() | nil,
          :required_conversation_resolution => boolean() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject65 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :required_status_checks,
      :struct,
      ExOctocat.Model.ReposOwnerRepoBranchesBranchProtectionRequiredStatusChecks,
      options
    )
    |> deserialize(
      :required_pull_request_reviews,
      :struct,
      ExOctocat.Model.ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviews,
      options
    )
    |> deserialize(
      :restrictions,
      :struct,
      ExOctocat.Model.ReposOwnerRepoBranchesBranchProtectionRestrictions,
      options
    )
  end
end
