# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineResponse20013 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total_count,
    :artifacts
  ]

  @type t :: %__MODULE__{
          :total_count => integer(),
          :artifacts => [ExOctocat.Model.Artifact.t()]
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineResponse20013 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:artifacts, :list, ExOctocat.Model.Artifact, options)
  end
end
