# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject71 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :state,
    :dismissed_reason
  ]

  @type t :: %__MODULE__{
          :state => ExOctocat.Model.CodeScanningAlertSetState.t(),
          :dismissed_reason => ExOctocat.Model.CodeScanningAlertDismissedReason.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject71 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:state, :struct, ExOctocat.Model.CodeScanningAlertSetState, options)
    |> deserialize(
      :dismissed_reason,
      :struct,
      ExOctocat.Model.CodeScanningAlertDismissedReason,
      options
    )
  end
end
