# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject136 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :subscribed,
    :ignored
  ]

  @type t :: %__MODULE__{
          :subscribed => boolean() | nil,
          :ignored => boolean() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject136 do
  def decode(value, _options) do
    value
  end
end
