# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject92 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :config,
    :events,
    :add_events,
    :remove_events,
    :active
  ]

  @type t :: %__MODULE__{
          :config => ExOctocat.Model.ReposOwnerRepoHooksHookIdConfig.t() | nil,
          :events => [String.t()] | nil,
          :add_events => [String.t()] | nil,
          :remove_events => [String.t()] | nil,
          :active => boolean() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject92 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :config,
      :struct,
      ExOctocat.Model.ReposOwnerRepoHooksHookIdConfig,
      options
    )
  end
end
