# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineResponse4032 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :message,
    :documentation_url,
    :errors
  ]

  @type t :: %__MODULE__{
          :message => String.t() | nil,
          :documentation_url => String.t() | nil,
          :errors => [ExOctocat.Model.InlineResponse4032Errors.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineResponse4032 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:errors, :list, ExOctocat.Model.InlineResponse4032Errors, options)
  end
end
