# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineResponse2021 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :message,
    :url
  ]

  @type t :: %__MODULE__{
          :message => String.t() | nil,
          :url => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineResponse2021 do
  def decode(value, _options) do
    value
  end
end
