# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject89 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :tag,
    :message,
    :object,
    :type,
    :tagger
  ]

  @type t :: %__MODULE__{
          :tag => String.t(),
          :message => String.t(),
          :object => String.t(),
          :type => String.t(),
          :tagger => ExOctocat.Model.ReposOwnerRepoGitTagsTagger.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject89 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:tagger, :struct, ExOctocat.Model.ReposOwnerRepoGitTagsTagger, options)
  end
end
