# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject80 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ref,
    :task,
    :auto_merge,
    :required_contexts,
    :payload,
    :environment,
    :description,
    :transient_environment,
    :production_environment
  ]

  @type t :: %__MODULE__{
          :ref => String.t(),
          :task => String.t() | nil,
          :auto_merge => boolean() | nil,
          :required_contexts => [String.t()] | nil,
          :payload => OneOfmapstring | nil,
          :environment => String.t() | nil,
          :description => String.t() | nil,
          :transient_environment => boolean() | nil,
          :production_environment => boolean() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject80 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:payload, :struct, ExOctocat.Model.OneOfmapstring, options)
  end
end
