# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject33 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :config,
    :events,
    :active,
    :name
  ]

  @type t :: %__MODULE__{
          :config => ExOctocat.Model.OrgsOrgHooksHookIdConfig.t() | nil,
          :events => [String.t()] | nil,
          :active => boolean() | nil,
          :name => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject33 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:config, :struct, ExOctocat.Model.OrgsOrgHooksHookIdConfig, options)
  end
end
