# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject90 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :tree,
    :base_tree
  ]

  @type t :: %__MODULE__{
          :tree => [ExOctocat.Model.ReposOwnerRepoGitTreesTree.t()],
          :base_tree => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject90 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:tree, :list, ExOctocat.Model.ReposOwnerRepoGitTreesTree, options)
  end
end
