# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineResponse2007 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total_count,
    :runner_groups
  ]

  @type t :: %__MODULE__{
          :total_count => float(),
          :runner_groups => [ExOctocat.Model.RunnerGroupsOrg.t()]
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineResponse2007 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:runner_groups, :list, ExOctocat.Model.RunnerGroupsOrg, options)
  end
end
