# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject53 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :position,
    :column_id
  ]

  @type t :: %__MODULE__{
          :position => String.t(),
          :column_id => integer() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject53 do
  def decode(value, _options) do
    value
  end
end
