# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject144 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :schemas,
    :userName,
    :name,
    :emails,
    :groups
  ]

  @type t :: %__MODULE__{
          :schemas => [String.t()],
          :userName => String.t(),
          :name => ExOctocat.Model.ScimV2EnterprisesEnterpriseUsersName.t(),
          :emails => [ExOctocat.Model.ScimV2EnterprisesEnterpriseUsersEmails.t()],
          :groups => [ExOctocat.Model.ScimV2EnterprisesEnterpriseUsersGroups.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject144 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :name,
      :struct,
      ExOctocat.Model.ScimV2EnterprisesEnterpriseUsersName,
      options
    )
    |> deserialize(
      :emails,
      :list,
      ExOctocat.Model.ScimV2EnterprisesEnterpriseUsersEmails,
      options
    )
    |> deserialize(
      :groups,
      :list,
      ExOctocat.Model.ScimV2EnterprisesEnterpriseUsersGroups,
      options
    )
  end
end
