# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject83 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :wait_timer,
    :reviewers,
    :deployment_branch_policy
  ]

  @type t :: %__MODULE__{
          :wait_timer => integer() | nil,
          :reviewers =>
            [ExOctocat.Model.ReposOwnerRepoEnvironmentsEnvironmentNameReviewers.t()] | nil,
          :deployment_branch_policy => ExOctocat.Model.DeploymentBranchPolicy.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject83 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :reviewers,
      :list,
      ExOctocat.Model.ReposOwnerRepoEnvironmentsEnvironmentNameReviewers,
      options
    )
    |> deserialize(
      :deployment_branch_policy,
      :struct,
      ExOctocat.Model.DeploymentBranchPolicy,
      options
    )
  end
end
