# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InlineObject125 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :commit_id,
    :body,
    :event,
    :comments
  ]

  @type t :: %__MODULE__{
          :commit_id => String.t() | nil,
          :body => String.t() | nil,
          :event => String.t() | nil,
          :comments =>
            [ExOctocat.Model.ReposOwnerRepoPullsPullNumberReviewsComments.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InlineObject125 do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :comments,
      :list,
      ExOctocat.Model.ReposOwnerRepoPullsPullNumberReviewsComments,
      options
    )
  end
end
