# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.InteractionLimit do
  @moduledoc """
  Limit interactions to a specific type of user for a specified duration
  """

  @derive [Poison.Encoder]
  defstruct [
    :limit,
    :expiry
  ]

  @type t :: %__MODULE__{
          :limit => ExOctocat.Model.InteractionGroup.t(),
          :expiry => ExOctocat.Model.InteractionExpiry.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.InteractionLimit do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:limit, :struct, ExOctocat.Model.InteractionGroup, options)
    |> deserialize(:expiry, :struct, ExOctocat.Model.InteractionExpiry, options)
  end
end
