# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.IssueEventForIssue do
  @moduledoc """
  Issue Event for Issue
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :node_id,
    :url,
    :actor,
    :event,
    :commit_id,
    :commit_url,
    :created_at,
    :performed_via_github_app,
    :label,
    :assignee,
    :assigner,
    :milestone,
    :rename,
    :review_requester,
    :requested_team,
    :requested_reviewer,
    :dismissed_review,
    :lock_reason,
    :project_card
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :node_id => String.t(),
          :url => String.t(),
          :actor => ExOctocat.Model.SimpleUser.t() | nil,
          :event => String.t(),
          :commit_id => String.t() | nil,
          :commit_url => String.t() | nil,
          :created_at => String.t(),
          :performed_via_github_app => ExOctocat.Model.Integration.t() | nil,
          :label => ExOctocat.Model.LabeledIssueEventLabel.t(),
          :assignee => ExOctocat.Model.SimpleUser.t() | nil,
          :assigner => ExOctocat.Model.SimpleUser.t() | nil,
          :milestone => ExOctocat.Model.MilestonedIssueEventMilestone.t(),
          :rename => ExOctocat.Model.RenamedIssueEventRename.t(),
          :review_requester => ExOctocat.Model.SimpleUser.t() | nil,
          :requested_team => ExOctocat.Model.Team.t() | nil,
          :requested_reviewer => ExOctocat.Model.SimpleUser.t() | nil,
          :dismissed_review => ExOctocat.Model.ReviewDismissedIssueEventDismissedReview.t(),
          :lock_reason => String.t() | nil,
          :project_card => ExOctocat.Model.AddedToProjectIssueEventProjectCard.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.IssueEventForIssue do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:actor, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:performed_via_github_app, :struct, ExOctocat.Model.Integration, options)
    |> deserialize(:label, :struct, ExOctocat.Model.LabeledIssueEventLabel, options)
    |> deserialize(:assignee, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:assigner, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(
      :milestone,
      :struct,
      ExOctocat.Model.MilestonedIssueEventMilestone,
      options
    )
    |> deserialize(:rename, :struct, ExOctocat.Model.RenamedIssueEventRename, options)
    |> deserialize(:review_requester, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:requested_team, :struct, ExOctocat.Model.Team, options)
    |> deserialize(:requested_reviewer, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(
      :dismissed_review,
      :struct,
      ExOctocat.Model.ReviewDismissedIssueEventDismissedReview,
      options
    )
    |> deserialize(
      :project_card,
      :struct,
      ExOctocat.Model.AddedToProjectIssueEventProjectCard,
      options
    )
  end
end
