# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.IssueEventLabel do
  @moduledoc """
  Issue Event Label
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :color
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :color => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.IssueEventLabel do
  def decode(value, _options) do
    value
  end
end
