# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.KeySimple do
  @moduledoc """
  Key Simple
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :key
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :key => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.KeySimple do
  def decode(value, _options) do
    value
  end
end
