# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.LabeledIssueEventLabel do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :color
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :color => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.LabeledIssueEventLabel do
  def decode(value, _options) do
    value
  end
end
