# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.OrgMembership do
  @moduledoc """
  Org Membership
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :state,
    :role,
    :organization_url,
    :organization,
    :user,
    :permissions
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :state => String.t(),
          :role => String.t(),
          :organization_url => String.t(),
          :organization => ExOctocat.Model.OrganizationSimple.t(),
          :user => SimpleUser | nil,
          :permissions => ExOctocat.Model.OrgMembershipPermissions.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.OrgMembership do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:organization, :struct, ExOctocat.Model.OrganizationSimple, options)
    |> deserialize(:user, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:permissions, :struct, ExOctocat.Model.OrgMembershipPermissions, options)
  end
end
