# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.PackageVersionMetadata do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :package_type,
    :container,
    :docker
  ]

  @type t :: %__MODULE__{
          :package_type => String.t(),
          :container => ExOctocat.Model.ContainerMetadata.t() | nil,
          :docker => ExOctocat.Model.DockerMetadata.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.PackageVersionMetadata do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:container, :struct, ExOctocat.Model.ContainerMetadata, options)
    |> deserialize(:docker, :struct, ExOctocat.Model.DockerMetadata, options)
  end
end
