# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.PackageVersion do
  @moduledoc """
  A version of a software package
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :url,
    :package_html_url,
    :html_url,
    :license,
    :description,
    :created_at,
    :updated_at,
    :deleted_at,
    :metadata
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :name => String.t(),
          :url => String.t(),
          :package_html_url => String.t(),
          :html_url => String.t() | nil,
          :license => String.t() | nil,
          :description => String.t() | nil,
          :created_at => DateTime.t(),
          :updated_at => DateTime.t(),
          :deleted_at => DateTime.t() | nil,
          :metadata => ExOctocat.Model.PackageVersionMetadata.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.PackageVersion do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:metadata, :struct, ExOctocat.Model.PackageVersionMetadata, options)
  end
end
