# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.PageBuildStatus do
  @moduledoc """
  Page Build Status
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :status
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :status => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.PageBuildStatus do
  def decode(value, _options) do
    value
  end
end
