# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.PagesHealthCheck do
  @moduledoc """
  Pages Health Check Status
  """

  @derive [Poison.Encoder]
  defstruct [
    :domain,
    :alt_domain
  ]

  @type t :: %__MODULE__{
          :domain => ExOctocat.Model.PagesHealthCheckDomain.t() | nil,
          :alt_domain => ExOctocat.Model.PagesHealthCheckAltDomain.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.PagesHealthCheck do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:domain, :struct, ExOctocat.Model.PagesHealthCheckDomain, options)
    |> deserialize(:alt_domain, :struct, ExOctocat.Model.PagesHealthCheckAltDomain, options)
  end
end
