# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.Page do
  @moduledoc """
  The configuration for GitHub Pages for a repository.
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :status,
    :cname,
    :custom_404,
    :html_url,
    :source,
    :public,
    :https_certificate,
    :https_enforced
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :status => String.t() | nil,
          :cname => String.t() | nil,
          :custom_404 => boolean(),
          :html_url => String.t() | nil,
          :source => ExOctocat.Model.PagesSourceHash.t() | nil,
          :public => boolean(),
          :https_certificate => ExOctocat.Model.PagesHttpsCertificate.t() | nil,
          :https_enforced => boolean() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.Page do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:source, :struct, ExOctocat.Model.PagesSourceHash, options)
    |> deserialize(
      :https_certificate,
      :struct,
      ExOctocat.Model.PagesHttpsCertificate,
      options
    )
  end
end
