# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.PendingDeploymentReviewers do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :reviewer
  ]

  @type t :: %__MODULE__{
          :type => ExOctocat.Model.DeploymentReviewerType.t() | nil,
          :reviewer => SimpleUser | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.PendingDeploymentReviewers do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:type, :struct, ExOctocat.Model.DeploymentReviewerType, options)
    |> deserialize(:reviewer, :struct, ExOctocat.Model.SimpleUser, options)
  end
end
