# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.PendingDeployment do
  @moduledoc """
  Details of a deployment that is waiting for protection rules to pass
  """

  @derive [Poison.Encoder]
  defstruct [
    :environment,
    :wait_timer,
    :wait_timer_started_at,
    :current_user_can_approve,
    :reviewers
  ]

  @type t :: %__MODULE__{
          :environment => ExOctocat.Model.PendingDeploymentEnvironment.t(),
          :wait_timer => integer(),
          :wait_timer_started_at => DateTime.t() | nil,
          :current_user_can_approve => boolean(),
          :reviewers => [ExOctocat.Model.PendingDeploymentReviewers.t()]
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.PendingDeployment do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :environment,
      :struct,
      ExOctocat.Model.PendingDeploymentEnvironment,
      options
    )
    |> deserialize(:reviewers, :list, ExOctocat.Model.PendingDeploymentReviewers, options)
  end
end
