# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ProjectColumn do
  @moduledoc """
  Project columns contain cards of work.
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :project_url,
    :cards_url,
    :id,
    :node_id,
    :name,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :project_url => String.t(),
          :cards_url => String.t(),
          :id => integer(),
          :node_id => String.t(),
          :name => String.t(),
          :created_at => DateTime.t(),
          :updated_at => DateTime.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ProjectColumn do
  def decode(value, _options) do
    value
  end
end
