# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ProjectCard do
  @moduledoc """
  Project cards represent a scope of work.
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :id,
    :node_id,
    :note,
    :creator,
    :created_at,
    :updated_at,
    :archived,
    :column_name,
    :project_id,
    :column_url,
    :content_url,
    :project_url
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :id => integer(),
          :node_id => String.t(),
          :note => String.t() | nil,
          :creator => SimpleUser | nil,
          :created_at => DateTime.t(),
          :updated_at => DateTime.t(),
          :archived => boolean() | nil,
          :column_name => String.t() | nil,
          :project_id => String.t() | nil,
          :column_url => String.t(),
          :content_url => String.t() | nil,
          :project_url => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ProjectCard do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:creator, :struct, ExOctocat.Model.SimpleUser, options)
  end
end
