# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ProtectedBranchPullRequestReviewDismissalRestrictions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :users,
    :teams,
    :url,
    :users_url,
    :teams_url
  ]

  @type t :: %__MODULE__{
          :users => [ExOctocat.Model.SimpleUser.t()] | nil,
          :teams => [ExOctocat.Model.Team.t()] | nil,
          :url => String.t() | nil,
          :users_url => String.t() | nil,
          :teams_url => String.t() | nil
        }
end

defimpl Poison.Decoder,
  for: ExOctocat.Model.ProtectedBranchPullRequestReviewDismissalRestrictions do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:users, :list, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:teams, :list, ExOctocat.Model.Team, options)
  end
end
