# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ProtectedBranch do
  @moduledoc """
  Branch protections protect branches
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :required_status_checks,
    :required_pull_request_reviews,
    :required_signatures,
    :enforce_admins,
    :required_linear_history,
    :allow_force_pushes,
    :allow_deletions,
    :restrictions,
    :required_conversation_resolution
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :required_status_checks => ExOctocat.Model.StatusCheckPolicy.t() | nil,
          :required_pull_request_reviews =>
            ExOctocat.Model.ProtectedBranchRequiredPullRequestReviews.t() | nil,
          :required_signatures =>
            ExOctocat.Model.BranchProtectionRequiredSignatures.t() | nil,
          :enforce_admins => ExOctocat.Model.ProtectedBranchEnforceAdmins.t() | nil,
          :required_linear_history =>
            ExOctocat.Model.ProtectedBranchRequiredLinearHistory.t() | nil,
          :allow_force_pushes =>
            ExOctocat.Model.ProtectedBranchRequiredLinearHistory.t() | nil,
          :allow_deletions =>
            ExOctocat.Model.ProtectedBranchRequiredLinearHistory.t() | nil,
          :restrictions => ExOctocat.Model.BranchRestrictionPolicy.t() | nil,
          :required_conversation_resolution =>
            ExOctocat.Model.BranchProtectionRequiredLinearHistory.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ProtectedBranch do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :required_status_checks,
      :struct,
      ExOctocat.Model.StatusCheckPolicy,
      options
    )
    |> deserialize(
      :required_pull_request_reviews,
      :struct,
      ExOctocat.Model.ProtectedBranchRequiredPullRequestReviews,
      options
    )
    |> deserialize(
      :required_signatures,
      :struct,
      ExOctocat.Model.BranchProtectionRequiredSignatures,
      options
    )
    |> deserialize(
      :enforce_admins,
      :struct,
      ExOctocat.Model.ProtectedBranchEnforceAdmins,
      options
    )
    |> deserialize(
      :required_linear_history,
      :struct,
      ExOctocat.Model.ProtectedBranchRequiredLinearHistory,
      options
    )
    |> deserialize(
      :allow_force_pushes,
      :struct,
      ExOctocat.Model.ProtectedBranchRequiredLinearHistory,
      options
    )
    |> deserialize(
      :allow_deletions,
      :struct,
      ExOctocat.Model.ProtectedBranchRequiredLinearHistory,
      options
    )
    |> deserialize(:restrictions, :struct, ExOctocat.Model.BranchRestrictionPolicy, options)
    |> deserialize(
      :required_conversation_resolution,
      :struct,
      ExOctocat.Model.BranchProtectionRequiredLinearHistory,
      options
    )
  end
end
