# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :users_url,
    :teams_url,
    :users,
    :teams
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :users_url => String.t(),
          :teams_url => String.t(),
          :users => [ExOctocat.Model.SimpleUser.t()],
          :teams => [ExOctocat.Model.Team.t()]
        }
end

defimpl Poison.Decoder,
  for: ExOctocat.Model.ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:users, :list, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:teams, :list, ExOctocat.Model.Team, options)
  end
end
