# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.PullRequestMinimal do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :number,
    :url,
    :head,
    :base
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :number => integer(),
          :url => String.t(),
          :head => ExOctocat.Model.PullRequestMinimalHead.t(),
          :base => ExOctocat.Model.PullRequestMinimalHead.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.PullRequestMinimal do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:head, :struct, ExOctocat.Model.PullRequestMinimalHead, options)
    |> deserialize(:base, :struct, ExOctocat.Model.PullRequestMinimalHead, options)
  end
end
