# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.PullRequestReviewRequest do
  @moduledoc """
  Pull Request Review Request
  """

  @derive [Poison.Encoder]
  defstruct [
    :users,
    :teams
  ]

  @type t :: %__MODULE__{
          :users => [ExOctocat.Model.SimpleUser.t()],
          :teams => [ExOctocat.Model.Team.t()]
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.PullRequestReviewRequest do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:users, :list, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:teams, :list, ExOctocat.Model.Team, options)
  end
end
