# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.PullRequestReviewCommentLinks do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :self,
    :html,
    :pull_request
  ]

  @type t :: %__MODULE__{
          :self => ExOctocat.Model.PullRequestReviewCommentLinksSelf.t(),
          :html => ExOctocat.Model.PullRequestReviewCommentLinksHtml.t(),
          :pull_request => ExOctocat.Model.PullRequestReviewCommentLinksPullRequest.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.PullRequestReviewCommentLinks do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :self,
      :struct,
      ExOctocat.Model.PullRequestReviewCommentLinksSelf,
      options
    )
    |> deserialize(
      :html,
      :struct,
      ExOctocat.Model.PullRequestReviewCommentLinksHtml,
      options
    )
    |> deserialize(
      :pull_request,
      :struct,
      ExOctocat.Model.PullRequestReviewCommentLinksPullRequest,
      options
    )
  end
end
