# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.PullRequestSimpleLinks do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :comments,
    :commits,
    :statuses,
    :html,
    :issue,
    :review_comments,
    :review_comment,
    :self
  ]

  @type t :: %__MODULE__{
          :comments => ExOctocat.Model.Link.t(),
          :commits => ExOctocat.Model.Link.t(),
          :statuses => ExOctocat.Model.Link.t(),
          :html => ExOctocat.Model.Link.t(),
          :issue => ExOctocat.Model.Link.t(),
          :review_comments => ExOctocat.Model.Link.t(),
          :review_comment => ExOctocat.Model.Link.t(),
          :self => ExOctocat.Model.Link.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.PullRequestSimpleLinks do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:comments, :struct, ExOctocat.Model.Link, options)
    |> deserialize(:commits, :struct, ExOctocat.Model.Link, options)
    |> deserialize(:statuses, :struct, ExOctocat.Model.Link, options)
    |> deserialize(:html, :struct, ExOctocat.Model.Link, options)
    |> deserialize(:issue, :struct, ExOctocat.Model.Link, options)
    |> deserialize(:review_comments, :struct, ExOctocat.Model.Link, options)
    |> deserialize(:review_comment, :struct, ExOctocat.Model.Link, options)
    |> deserialize(:self, :struct, ExOctocat.Model.Link, options)
  end
end
