# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.RateLimitOverviewResources do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :core,
    :graphql,
    :search,
    :source_import,
    :integration_manifest,
    :code_scanning_upload
  ]

  @type t :: %__MODULE__{
          :core => ExOctocat.Model.RateLimit.t(),
          :graphql => ExOctocat.Model.RateLimit.t() | nil,
          :search => ExOctocat.Model.RateLimit.t(),
          :source_import => ExOctocat.Model.RateLimit.t() | nil,
          :integration_manifest => ExOctocat.Model.RateLimit.t() | nil,
          :code_scanning_upload => ExOctocat.Model.RateLimit.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.RateLimitOverviewResources do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:core, :struct, ExOctocat.Model.RateLimit, options)
    |> deserialize(:graphql, :struct, ExOctocat.Model.RateLimit, options)
    |> deserialize(:search, :struct, ExOctocat.Model.RateLimit, options)
    |> deserialize(:source_import, :struct, ExOctocat.Model.RateLimit, options)
    |> deserialize(:integration_manifest, :struct, ExOctocat.Model.RateLimit, options)
    |> deserialize(:code_scanning_upload, :struct, ExOctocat.Model.RateLimit, options)
  end
end
