# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.Reaction do
  @moduledoc """
  Reactions to conversations provide a way to help people express their feelings more simply and effectively.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :node_id,
    :user,
    :content,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :node_id => String.t(),
          :user => SimpleUser | nil,
          :content => String.t(),
          :created_at => DateTime.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.Reaction do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:user, :struct, ExOctocat.Model.SimpleUser, options)
  end
end
