# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ReferrerTraffic do
  @moduledoc """
  Referrer Traffic
  """

  @derive [Poison.Encoder]
  defstruct [
    :referrer,
    :count,
    :uniques
  ]

  @type t :: %__MODULE__{
          :referrer => String.t(),
          :count => integer(),
          :uniques => integer()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ReferrerTraffic do
  def decode(value, _options) do
    value
  end
end
