# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.RepositoryInvitation do
  @moduledoc """
  Repository invitations let you manage who you collaborate with.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :repository,
    :invitee,
    :inviter,
    :permissions,
    :created_at,
    :expired,
    :url,
    :html_url,
    :node_id
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :repository => ExOctocat.Model.MinimalRepository.t(),
          :invitee => SimpleUser | nil,
          :inviter => SimpleUser | nil,
          :permissions => String.t(),
          :created_at => DateTime.t(),
          :expired => boolean() | nil,
          :url => String.t(),
          :html_url => String.t(),
          :node_id => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.RepositoryInvitation do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:repository, :struct, ExOctocat.Model.MinimalRepository, options)
    |> deserialize(:invitee, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:inviter, :struct, ExOctocat.Model.SimpleUser, options)
  end
end
