# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ScimUser do
  @moduledoc """
  SCIM /Users provisioning endpoints
  """

  @derive [Poison.Encoder]
  defstruct [
    :schemas,
    :id,
    :externalId,
    :userName,
    :displayName,
    :name,
    :emails,
    :active,
    :meta,
    :organization_id,
    :operations,
    :groups
  ]

  @type t :: %__MODULE__{
          :schemas => [String.t()],
          :id => String.t(),
          :externalId => String.t() | nil,
          :userName => String.t() | nil,
          :displayName => String.t() | nil,
          :name => ExOctocat.Model.ScimUserName.t(),
          :emails => [ExOctocat.Model.ScimUserEmails.t()],
          :active => boolean(),
          :meta => ExOctocat.Model.ScimUserMeta.t(),
          :organization_id => integer() | nil,
          :operations => [ExOctocat.Model.ScimUserOperations.t()] | nil,
          :groups => [map()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ScimUser do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:name, :struct, ExOctocat.Model.ScimUserName, options)
    |> deserialize(:emails, :list, ExOctocat.Model.ScimUserEmails, options)
    |> deserialize(:meta, :struct, ExOctocat.Model.ScimUserMeta, options)
    |> deserialize(:operations, :list, ExOctocat.Model.ScimUserOperations, options)
  end
end
