# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ScimEnterpriseGroup do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :schemas,
    :id,
    :externalId,
    :displayName,
    :members,
    :meta
  ]

  @type t :: %__MODULE__{
          :schemas => [String.t()],
          :id => String.t(),
          :externalId => String.t() | nil,
          :displayName => String.t() | nil,
          :members => [ExOctocat.Model.ScimGroupListEnterpriseMembers.t()] | nil,
          :meta => ExOctocat.Model.ScimGroupListEnterpriseMeta.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ScimEnterpriseGroup do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:members, :list, ExOctocat.Model.ScimGroupListEnterpriseMembers, options)
    |> deserialize(:meta, :struct, ExOctocat.Model.ScimGroupListEnterpriseMeta, options)
  end
end
