# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ScimError do
  @moduledoc """
  Scim Error
  """

  @derive [Poison.Encoder]
  defstruct [
    :message,
    :documentation_url,
    :detail,
    :status,
    :scimType,
    :schemas
  ]

  @type t :: %__MODULE__{
          :message => String.t() | nil,
          :documentation_url => String.t() | nil,
          :detail => String.t() | nil,
          :status => integer() | nil,
          :scimType => String.t() | nil,
          :schemas => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ScimError do
  def decode(value, _options) do
    value
  end
end
