# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ScimUserList do
  @moduledoc """
  SCIM User List
  """

  @derive [Poison.Encoder]
  defstruct [
    :schemas,
    :totalResults,
    :itemsPerPage,
    :startIndex,
    :Resources
  ]

  @type t :: %__MODULE__{
          :schemas => [String.t()],
          :totalResults => integer(),
          :itemsPerPage => integer(),
          :startIndex => integer(),
          :Resources => [ExOctocat.Model.ScimUser.t()]
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ScimUserList do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Resources, :list, ExOctocat.Model.ScimUser, options)
  end
end
