# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ScimUserListEnterprise do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :schemas,
    :totalResults,
    :itemsPerPage,
    :startIndex,
    :Resources
  ]

  @type t :: %__MODULE__{
          :schemas => [String.t()],
          :totalResults => float(),
          :itemsPerPage => float(),
          :startIndex => float(),
          :Resources => [ExOctocat.Model.ScimUserListEnterpriseResources.t()]
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ScimUserListEnterprise do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :Resources,
      :list,
      ExOctocat.Model.ScimUserListEnterpriseResources,
      options
    )
  end
end
