# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ScimGroupListEnterpriseMeta do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :resourceType,
    :created,
    :lastModified,
    :location
  ]

  @type t :: %__MODULE__{
          :resourceType => String.t() | nil,
          :created => String.t() | nil,
          :lastModified => String.t() | nil,
          :location => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ScimGroupListEnterpriseMeta do
  def decode(value, _options) do
    value
  end
end
