# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.SecretScanningAlert do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :created_at,
    :url,
    :html_url,
    :state,
    :resolution,
    :resolved_at,
    :resolved_by,
    :secret_type,
    :secret
  ]

  @type t :: %__MODULE__{
          :number => integer() | nil,
          :created_at => DateTime.t() | nil,
          :url => String.t() | nil,
          :html_url => String.t() | nil,
          :state => ExOctocat.Model.SecretScanningAlertState.t() | nil,
          :resolution => ExOctocat.Model.SecretScanningAlertResolution.t() | nil,
          :resolved_at => DateTime.t() | nil,
          :resolved_by => ExOctocat.Model.SimpleUser.t() | nil,
          :secret_type => String.t() | nil,
          :secret => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.SecretScanningAlert do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:state, :struct, ExOctocat.Model.SecretScanningAlertState, options)
    |> deserialize(
      :resolution,
      :struct,
      ExOctocat.Model.SecretScanningAlertResolution,
      options
    )
    |> deserialize(:resolved_by, :struct, ExOctocat.Model.SimpleUser, options)
  end
end
