# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ShortBlob do
  @moduledoc """
  Short Blob
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :sha
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :sha => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ShortBlob do
  def decode(value, _options) do
    value
  end
end
