# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.StarredRepository do
  @moduledoc """
  Starred Repository
  """

  @derive [Poison.Encoder]
  defstruct [
    :starred_at,
    :repo
  ]

  @type t :: %__MODULE__{
          :starred_at => DateTime.t(),
          :repo => ExOctocat.Model.Repository.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.StarredRepository do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:repo, :struct, ExOctocat.Model.Repository, options)
  end
end
