# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.Tag do
  @moduledoc """
  Tag
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :commit,
    :zipball_url,
    :tarball_url,
    :node_id
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :commit => ExOctocat.Model.ShortBranchCommit.t(),
          :zipball_url => String.t(),
          :tarball_url => String.t(),
          :node_id => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.Tag do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:commit, :struct, ExOctocat.Model.ShortBranchCommit, options)
  end
end
