# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.Team do
  @moduledoc """
  Groups of organization members that gives permissions on specified repositories.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :node_id,
    :name,
    :slug,
    :description,
    :privacy,
    :permission,
    :permissions,
    :url,
    :html_url,
    :members_url,
    :repositories_url,
    :parent
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :node_id => String.t(),
          :name => String.t(),
          :slug => String.t(),
          :description => String.t() | nil,
          :privacy => String.t() | nil,
          :permission => String.t(),
          :permissions => ExOctocat.Model.TeamPermissions.t() | nil,
          :url => String.t(),
          :html_url => String.t(),
          :members_url => String.t(),
          :repositories_url => String.t(),
          :parent => TeamSimple | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.Team do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:permissions, :struct, ExOctocat.Model.TeamPermissions, options)
    |> deserialize(:parent, :struct, ExOctocat.Model.TeamSimple, options)
  end
end
