# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.TeamProject do
  @moduledoc """
  A team's access to a project.
  """

  @derive [Poison.Encoder]
  defstruct [
    :owner_url,
    :url,
    :html_url,
    :columns_url,
    :id,
    :node_id,
    :name,
    :body,
    :number,
    :state,
    :creator,
    :created_at,
    :updated_at,
    :organization_permission,
    :private,
    :permissions
  ]

  @type t :: %__MODULE__{
          :owner_url => String.t(),
          :url => String.t(),
          :html_url => String.t(),
          :columns_url => String.t(),
          :id => integer(),
          :node_id => String.t(),
          :name => String.t(),
          :body => String.t() | nil,
          :number => integer(),
          :state => String.t(),
          :creator => ExOctocat.Model.SimpleUser.t() | nil,
          :created_at => String.t(),
          :updated_at => String.t(),
          :organization_permission => String.t() | nil,
          :private => boolean() | nil,
          :permissions => ExOctocat.Model.TeamProjectPermissions.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.TeamProject do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:creator, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:permissions, :struct, ExOctocat.Model.TeamProjectPermissions, options)
  end
end
