# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.TeamFull do
  @moduledoc """
  Groups of organization members that gives permissions on specified repositories.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :node_id,
    :url,
    :html_url,
    :name,
    :slug,
    :description,
    :privacy,
    :permission,
    :members_url,
    :repositories_url,
    :parent,
    :members_count,
    :repos_count,
    :created_at,
    :updated_at,
    :organization,
    :ldap_dn
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :node_id => String.t(),
          :url => String.t(),
          :html_url => String.t(),
          :name => String.t(),
          :slug => String.t(),
          :description => String.t() | nil,
          :privacy => String.t() | nil,
          :permission => String.t(),
          :members_url => String.t(),
          :repositories_url => String.t(),
          :parent => TeamSimple | nil,
          :members_count => integer(),
          :repos_count => integer(),
          :created_at => DateTime.t(),
          :updated_at => DateTime.t(),
          :organization => ExOctocat.Model.OrganizationFull.t(),
          :ldap_dn => String.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.TeamFull do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:parent, :struct, ExOctocat.Model.TeamSimple, options)
    |> deserialize(:organization, :struct, ExOctocat.Model.OrganizationFull, options)
  end
end
