# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ThreadSubject do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :url,
    :latest_comment_url,
    :type
  ]

  @type t :: %__MODULE__{
          :title => String.t(),
          :url => String.t(),
          :latest_comment_url => String.t(),
          :type => String.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ThreadSubject do
  def decode(value, _options) do
    value
  end
end
