# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.TimelineLineCommentedEvent do
  @moduledoc """
  Timeline Line Commented Event
  """

  @derive [Poison.Encoder]
  defstruct [
    :event,
    :node_id,
    :comments
  ]

  @type t :: %__MODULE__{
          :event => String.t() | nil,
          :node_id => String.t() | nil,
          :comments => [ExOctocat.Model.PullRequestReviewComment.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.TimelineLineCommentedEvent do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:comments, :list, ExOctocat.Model.PullRequestReviewComment, options)
  end
end
