# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.TimelineCommentEvent do
  @moduledoc """
  Timeline Comment Event
  """

  @derive [Poison.Encoder]
  defstruct [
    :event,
    :actor,
    :id,
    :node_id,
    :url,
    :body,
    :body_text,
    :body_html,
    :html_url,
    :user,
    :created_at,
    :updated_at,
    :issue_url,
    :author_association,
    :performed_via_github_app,
    :reactions
  ]

  @type t :: %__MODULE__{
          :event => String.t(),
          :actor => ExOctocat.Model.SimpleUser.t() | nil,
          :id => integer(),
          :node_id => String.t(),
          :url => String.t(),
          :body => String.t() | nil,
          :body_text => String.t() | nil,
          :body_html => String.t() | nil,
          :html_url => String.t(),
          :user => ExOctocat.Model.SimpleUser.t() | nil,
          :created_at => DateTime.t(),
          :updated_at => DateTime.t(),
          :issue_url => String.t(),
          :author_association => ExOctocat.Model.AuthorAssociation.t(),
          :performed_via_github_app => ExOctocat.Model.Integration.t() | nil,
          :reactions => ExOctocat.Model.ReactionRollup.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.TimelineCommentEvent do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:actor, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:user, :struct, ExOctocat.Model.SimpleUser, options)
    |> deserialize(:author_association, :struct, ExOctocat.Model.AuthorAssociation, options)
    |> deserialize(:performed_via_github_app, :struct, ExOctocat.Model.Integration, options)
    |> deserialize(:reactions, :struct, ExOctocat.Model.ReactionRollup, options)
  end
end
