# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.TimelineReviewedEventLinks do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :html,
    :pull_request
  ]

  @type t :: %__MODULE__{
          :html => ExOctocat.Model.TimelineReviewedEventLinksHtml.t(),
          :pull_request => ExOctocat.Model.TimelineReviewedEventLinksHtml.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.TimelineReviewedEventLinks do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:html, :struct, ExOctocat.Model.TimelineReviewedEventLinksHtml, options)
    |> deserialize(
      :pull_request,
      :struct,
      ExOctocat.Model.TimelineReviewedEventLinksHtml,
      options
    )
  end
end
