# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.Topic do
  @moduledoc """
  A topic aggregates entities that are related to a subject.
  """

  @derive [Poison.Encoder]
  defstruct [
    :names
  ]

  @type t :: %__MODULE__{
          :names => [String.t()]
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.Topic do
  def decode(value, _options) do
    value
  end
end
