# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.ValidationErrorSimple do
  @moduledoc """
  Validation Error Simple
  """

  @derive [Poison.Encoder]
  defstruct [
    :message,
    :documentation_url,
    :errors
  ]

  @type t :: %__MODULE__{
          :message => String.t(),
          :documentation_url => String.t(),
          :errors => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.ValidationErrorSimple do
  def decode(value, _options) do
    value
  end
end
