# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.WebhookConfig do
  @moduledoc """
  Configuration object of the webhook
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :content_type,
    :secret,
    :insecure_ssl
  ]

  @type t :: %__MODULE__{
          :url => String.t() | nil,
          :content_type => String.t() | nil,
          :secret => String.t() | nil,
          :insecure_ssl => ExOctocat.Model.WebhookConfigInsecureSsl.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.WebhookConfig do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :insecure_ssl,
      :struct,
      ExOctocat.Model.WebhookConfigInsecureSsl,
      options
    )
  end
end
