# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.WorkflowUsageBillableUbuntu do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total_ms
  ]

  @type t :: %__MODULE__{
          :total_ms => integer() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.WorkflowUsageBillableUbuntu do
  def decode(value, _options) do
    value
  end
end
