# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.WorkflowRunUsage do
  @moduledoc """
  Workflow Run Usage
  """

  @derive [Poison.Encoder]
  defstruct [
    :billable,
    :run_duration_ms
  ]

  @type t :: %__MODULE__{
          :billable => ExOctocat.Model.WorkflowRunUsageBillable.t(),
          :run_duration_ms => integer() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.WorkflowRunUsage do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:billable, :struct, ExOctocat.Model.WorkflowRunUsageBillable, options)
  end
end
