# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.WorkflowUsage do
  @moduledoc """
  Workflow Usage
  """

  @derive [Poison.Encoder]
  defstruct [
    :billable
  ]

  @type t :: %__MODULE__{
          :billable => ExOctocat.Model.WorkflowUsageBillable.t()
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.WorkflowUsage do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:billable, :struct, ExOctocat.Model.WorkflowUsageBillable, options)
  end
end
