# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.WorkflowRunUsageBillable do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :UBUNTU,
    :MACOS,
    :WINDOWS
  ]

  @type t :: %__MODULE__{
          :UBUNTU => ExOctocat.Model.WorkflowRunUsageBillableUbuntu.t() | nil,
          :MACOS => ExOctocat.Model.WorkflowRunUsageBillableUbuntu.t() | nil,
          :WINDOWS => ExOctocat.Model.WorkflowRunUsageBillableUbuntu.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.WorkflowRunUsageBillable do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :UBUNTU,
      :struct,
      ExOctocat.Model.WorkflowRunUsageBillableUbuntu,
      options
    )
    |> deserialize(:MACOS, :struct, ExOctocat.Model.WorkflowRunUsageBillableUbuntu, options)
    |> deserialize(
      :WINDOWS,
      :struct,
      ExOctocat.Model.WorkflowRunUsageBillableUbuntu,
      options
    )
  end
end
