# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Model.WorkflowUsageBillable do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :UBUNTU,
    :MACOS,
    :WINDOWS
  ]

  @type t :: %__MODULE__{
          :UBUNTU => ExOctocat.Model.WorkflowUsageBillableUbuntu.t() | nil,
          :MACOS => ExOctocat.Model.WorkflowUsageBillableUbuntu.t() | nil,
          :WINDOWS => ExOctocat.Model.WorkflowUsageBillableUbuntu.t() | nil
        }
end

defimpl Poison.Decoder, for: ExOctocat.Model.WorkflowUsageBillable do
  import ExOctocat.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:UBUNTU, :struct, ExOctocat.Model.WorkflowUsageBillableUbuntu, options)
    |> deserialize(:MACOS, :struct, ExOctocat.Model.WorkflowUsageBillableUbuntu, options)
    |> deserialize(:WINDOWS, :struct, ExOctocat.Model.WorkflowUsageBillableUbuntu, options)
  end
end
