# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule ExOctocat.Connection do
  @moduledoc """
  Handle Tesla connections for ExOctocat.
  """

  use Tesla

  # Add any middleware here (authentication)
  plug(Tesla.Middleware.BaseUrl, "https://api.github.com")
  plug(Tesla.Middleware.Headers, [{"user-agent", "Elixir"}])
  plug(Tesla.Middleware.EncodeJson, engine: Poison)
  plug(Tesla.Middleware.FollowRedirects)

  @doc """
  Configure an authless client connection

  # Returns

  Tesla.Env.client
  """
  @spec new(binary()) :: Tesla.Env.client()
  def new(token, opts \\ []) do
    middleware = [
      {Tesla.Middleware.BearerAuth, token: token}
    ]

    middleware =
      if(opts |> Keyword.get(:log, true)) do
        [Tesla.Middleware.Logger | middleware]
      else
        middleware
      end

    Tesla.client(middleware)
  end
end
